'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated from a template.
'
'     Manual changes to this file may cause unexpected behavior in your application.
'     Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class OrderDetail
    Public Property OrderDetailId As Integer
    Public Property OrderDate As Nullable(Of Date)
    Public Property Username As String
    Public Property FirstName As String
    Public Property LastName As String
    Public Property Address As String
    Public Property City As String
    Public Property State As String
    Public Property PostalCode As String
    Public Property Country As String
    Public Property Telephone As String
    Public Property Email As String
    Public Property Subtotal As Nullable(Of Decimal)
    Public Property Tax As Nullable(Of Decimal)
    Public Property Total As Nullable(Of Decimal)
    Public Property PaymentMethod As String

    Public Overridable Property Orders As ICollection(Of Order) = New HashSet(Of Order)

End Class
