'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated from a template.
'
'     Manual changes to this file may cause unexpected behavior in your application.
'     Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class Order
    Public Property OrderId As Integer
    Public Property ProductId As Integer
    Public Property OrderDetailId As Nullable(Of Integer)
    Public Property Quantity As Nullable(Of Integer)

    Public Overridable Property OrderDetail As OrderDetail
    Public Overridable Property Product As Product

End Class
