'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated from a template.
'
'     Manual changes to this file may cause unexpected behavior in your application.
'     Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class Album
    Public Property AlbumId As Integer
    Public Property GenreId As Integer
    Public Property ArtistId As Integer
    Public Property Title As String
    Public Property Price As Decimal
    Public Property AlbumArtUrl As String

    Public Overridable Property Artist As Artist
    Public Overridable Property Genre As Genre
    Public Overridable Property Carts As ICollection(Of Cart) = New HashSet(Of Cart)
    Public Overridable Property OrderDetails As ICollection(Of OrderDetail) = New HashSet(Of OrderDetail)

End Class
