'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated from a template.
'
'     Manual changes to this file may cause unexpected behavior in your application.
'     Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class Artist
    Public Property ArtistId As Integer
    Public Property Name As String

    Public Overridable Property Albums As ICollection(Of Album) = New HashSet(Of Album)
    Public Overridable Property Images As ICollection(Of Image) = New HashSet(Of Image)
    Public Overridable Property Videos As ICollection(Of Video) = New HashSet(Of Video)

End Class
