'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated from a template.
'
'     Manual changes to this file may cause unexpected behavior in your application.
'     Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class Cart
    Public Property RecordId As Integer
    Public Property CartId As String
    Public Property AlbumId As Integer
    Public Property Count As Integer
    Public Property DateCreated As Date

    Public Overridable Property Album As Album

End Class
