'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated from a template.
'
'     Manual changes to this file may cause unexpected behavior in your application.
'     Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class Image
    Public Property ImageId As Integer
    Public Property ArtistId As Integer
    Public Property OriginalPath As String
    Public Property Title As String
    Public Property Price As Decimal
    Public Property ImageData As Byte()

    Public Overridable Property Artist As Artist

End Class
