'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated from a template.
'
'     Manual changes to this file may cause unexpected behavior in your application.
'     Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Data.Entity
Imports System.Data.Entity.Infrastructure

Partial Public Class MediaCollectionEntities
    Inherits DbContext

    Public Sub New()
        MyBase.New("name=MediaCollectionEntities")
    End Sub

    Protected Overrides Sub OnModelCreating(modelBuilder As DbModelBuilder)
        Throw New UnintentionalCodeFirstException()
    End Sub

    Public Overridable Property Albums() As DbSet(Of Album)
    Public Overridable Property Artists() As DbSet(Of Artist)
    Public Overridable Property Artists1() As DbSet(Of Artist1)
    Public Overridable Property Carts() As DbSet(Of Cart)
    Public Overridable Property Genres() As DbSet(Of Genre)
    Public Overridable Property Orders() As DbSet(Of Order)
    Public Overridable Property OrderDetails() As DbSet(Of OrderDetail)
    Public Overridable Property Tables() As DbSet(Of Table)
    Public Overridable Property Images() As DbSet(Of Image)
    Public Overridable Property Videos() As DbSet(Of Video)

End Class
