'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated from a template.
'
'     Manual changes to this file may cause unexpected behavior in your application.
'     Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class OrderDetail
    Public Property OrderDetailId As Integer
    Public Property OrderId As Integer
    Public Property AlbumId As Integer
    Public Property ImageId As Integer
    Public Property VideoId As Integer
    Public Property Quantity As Integer
    Public Property UnitPrice As Decimal

    Public Overridable Property Album As Album
    Public Overridable Property Order As Order

End Class
