'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated from a template.
'
'     Manual changes to this file may cause unexpected behavior in your application.
'     Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class Video
    Public Property VideoId As Integer
    Public Property ArtistId As Integer
    Public Property OriginalPath As String
    Public Property Title As String
    Public Property Price As Decimal

    Public Overridable Property Artist As Artist

End Class
